let attractor = {
  name: "Clifford",
  type: "2d",
  functions: {
    x: function(p) {
      return function(x, y) {
        return Math.sin(p[0]*y) + p[2] * Math.cos(p[0]*x);
      }
    },
    y: function(p) {
      return function(x, y) {
        return Math.sin(p[1]*x) + p[3] * Math.cos(p[1]*y);
      }
    }
  },
  variations: [
    {
      paramsStable: [-1.3, -1.3, -1.8, -1.9],
      iterStable: 8500,
      tolStable: 1000,
      transWidth: 2,
      transHeight: 2,
      scale: 7,
      initVals: [0,0],
      canTol: true,
      weightLow: 1.3,
      weightHigh: 2,
      weightTransHeight: 200,
    },
    {
      paramsStable: [-1.4, 1.6, 1.0, 0.7],
      iterStable: 8500,
      tolStable: 1000,
      transWidth: 2,
      transHeight: 2,
      scale: 5,
      initVals: [0,0],
      canTol: true,
      weightLow: 1.3,
      weightHigh: 2,
      weightTransHeight: 200,
    },
    {
      paramsStable: [1.7, 1.7, 0.6, 1.2],
      iterStable: 8500,
      tolStable: 1000,
      transWidth: 2,
      transHeight: 2,
      scale: 6,
      initVals: [0,0],
      canTol: true,
      weightLow: 1.3,
      weightHigh: 2,
      weightTransHeight: 200,
    },
    {
      paramsStable: [1.7, 0.7, 1.4, 2],
      iterStable: 8500,
      tolStable: 1000,
      transWidth: 2,
      transHeight: 2.5,
      scale: 6,
      initVals: [0,0],
      canTol: true,
      weightLow: 1.3,
      weightHigh: 2,
      weightTransHeight: 200,
    },
    {
      paramsStable: [-1.7, 1.8, -1.9, -0.4],
      iterStable: 8500,
      tolStable: 1000,
      transWidth: 2,
      transHeight: 2,
      scale: 6,
      initVals: [0,0],
      canTol: true,
      weightLow: 1.3,
      weightHigh: 2,
      weightTransHeight: 200,
    },
    {
      paramsStable: [1.1, -1.32, -1.03, 1.54],
      iterStable: 8500,
      tolStable: 1000,
      transWidth: 1.9,
      transHeight: 2,
      scale: 6,
      initVals: [0,0],
      canTol: true,
      weightLow: 1.3,
      weightHigh: 2,
      weightTransHeight: 200,
    },
    {
      paramsStable: [-1.9, -1.9, -1.9, -1.0],
      iterStable: 8500,
      tolStable: 1000,
      transWidth: 2,
      transHeight: 2,
      scale: 6,
      initVals: [0,0],
      canTol: true,
      weightLow: 1.3,
      weightHigh: 2,
      weightTransHeight: 200,
    },
    {
      paramsStable: [-1.32, -1.65, 0.74, 1.81],
      iterStable: 8500,
      tolStable: 1000,
      transWidth: 2,
      transHeight: 1.9,
      scale: 6.5,
      initVals: [0,0],
      canTol: false,
      weightLow: 1.3,
      weightHigh: 2,
      weightTransHeight: 200,
    },
    {
      paramsStable: [-1.6, 1.6, 0.7, -1],
      iterStable: 8500,
      tolStable: 1000,
      transWidth: 2,
      transHeight: 2,
      scale: 6,
      initVals: [0,0],
      canTol: true,
      weightLow: 1.3,
      weightHigh: 2,
      weightTransHeight: 200,
    },
    {
      paramsStable: [-1.7, 1.5, -0.5, 0.7],
      iterStable: 8500,
      tolStable: 1000,
      transWidth: 2,
      transHeight: 2,
      scale: 5,
      initVals: [0,0],
      canTol: true,
      weightLow: 1.3,
      weightHigh: 2,
      weightTransHeight: 200,
    },
    {
      paramsStable: [1.6, -0.6, -1.2, 1.6],
      iterStable: 12500,
      tolStable: 1000,
      transWidth: 2,
      transHeight: 3.5,
      scale: 4.5,
      initVals: [0,0],
      canTol: false,
      weightLow: 1.3,
      weightHigh: 1.7,
      weightTransHeight: 200,
    },
    {
      paramsStable: [0.77, 1.99, -1.31, -1.45],
      iterStable: 8500,
      tolStable: 1000,
      transWidth: 1.65,
      transHeight: 2,
      scale: 6,
      initVals: [0,0],
      canTol: true,
      weightLow: 1.3,
      weightHigh: 2,
      weightTransHeight: 200,
    },
    {
      paramsStable: [0.75, 1.34, -1.93, 1],
      iterStable: 12500,
      tolStable: 1000,
      transWidth: 1.75,
      transHeight: 2,
      scale: 6,
      initVals: [0,0],
      canTol: false,
      weightLow: 1.3,
      weightHigh: 1.7,
      weightTransHeight: 200,
    },
    {
      paramsStable: [1.5, -1.8, 1.6, 0.9],
      iterStable: 12500,
      tolStable: 1000,
      transWidth: 2,
      transHeight: 2,
      scale: 6,
      initVals: [0,0],
      canTol: true,
      weightLow: 1.3,
      weightHigh: 1.7,
      weightTransHeight: 200,
    },
    {
      paramsStable: [-1.7, 1.3, -0.1, -1.2],
      iterStable: 12500,
      tolStable: 1000,
      transWidth: 2,
      transHeight: 1.9,
      scale: 6,
      initVals: [0,0],
      canTol: true,
      weightLow: 1.3,
      weightHigh: 1.7,
      weightTransHeight: 200,
    },
    {
      paramsStable: [-1.8, -2.0, -0.5, -0.9],
      iterStable: 12500,
      tolStable: 1000,
      transWidth: 2,
      transHeight: 2,
      scale: 5,
      initVals: [0,0],
      canTol: true,
      weightLow: 1.3,
      weightHigh: 1.7,
      weightTransHeight: 200,
    },
  ]
}

export {attractor};