let attractor = {
  name: "Peter de Jong",
  type: "2d",
  functions: {
    x: function (p) {
      return function (x, y) {
        return Math.sin(p[0] * y) - Math.cos(p[1] * x);
      }
    },
    y: function (p) {
      return function (x, y) {
        return Math.sin(p[2] * x) - Math.cos(p[3] * y);
      }
    },
  },
  variations: [
    {
      paramsStable: [1.641, 1.902, 0.316, 1.525],
      iterStable: 7000,
      tolStable: 1000,
      transWidth: 2,
      transHeight: 2,
      scale: 5,
      initVals: [0, 0],
      canTol: true,
      weightLow: 1.2,
      weightHigh: 2,
      weightTransHeight: 200,
    },
    {
      paramsStable: [1.4, -2.3, 2.4, -2.1],
      iterStable: 7000,
      tolStable: 1000,
      transWidth: 2,
      transHeight: 2,
      scale: 6,
      initVals: [0, 0],
      canTol: true,
      weightLow: 1.3,
      weightHigh: 2,
      weightTransHeight: 200,
    },
    {
      paramsStable: [2.01, -2.53, 1.61, -0.33],
      iterStable: 7000,
      tolStable: 1000,
      transWidth: 2,
      transHeight: 2,
      scale: 6,
      initVals: [0, 0],
      canTol: true,
      weightLow: 1.3,
      weightHigh: 2,
      weightTransHeight: 200,
    },
    {
      paramsStable: [-2, -2, -1.2, 2],
      iterStable: 7000,
      tolStable: 1000,
      transWidth: 2,
      transHeight: 2,
      scale: 6,
      initVals: [0, 0],
      canTol: true,
      weightLow: 1.3,
      weightHigh: 2,
      weightTransHeight: 200,
    },
    {
      paramsStable: [-0.827, -1.637, 1.659, -0.943],
      iterStable: 7000,
      tolStable: 1000,
      transWidth: 2,
      transHeight: 2,
      scale: 6,
      initVals: [0, 0],
      canTol: true,
      weightLow: 1.3,
      weightHigh: 2,
      weightTransHeight: 200,
    },
    {
      paramsStable: [0.970, -1.899, 1.381, -1.506],
      iterStable: 7000,
      tolStable: 1000,
      transWidth: 2,
      transHeight: 2,
      scale: 6,
      initVals: [0, 0],
      canTol: true,
      weightLow: 1.3,
      weightHigh: 2,
      weightTransHeight: 200,
    },
    {
      paramsStable: [-1.244, -1.251, -1.815, -1.908],
      iterStable: 7000,
      tolStable: 1000,
      transWidth: 2,
      transHeight: 2,
      scale: 6,
      initVals: [0, 0],
      canTol: true,
      weightLow: 1.3,
      weightHigh: 2,
    },
    {
      paramsStable: [1.7, 1.7, 0.6, 1.2],
      iterStable: 7000,
      tolStable: 1000,
      transWidth: 2,
      transHeight: 2,
      scale: 6,
      initVals: [0, 0],
      canTol: true,
      weightLow: 1.3,
      weightHigh: 2,
      weightTransHeight: 200,
    },
    {
      paramsStable: [-2.24, 0.43, -0.65, -2.43],
      iterStable: 7000,
      tolStable: 1000,
      transWidth: 1.55,
      transHeight: 2.5,
      scale: 4.5,
      initVals: [0, 0],
      canTol: true,
      weightLow: 1.3,
      weightHigh: 2,
      weightTransHeight: 200,
    },
    {
      paramsStable: [-2.7, -0.09, -0.86, -2.2],
      iterStable: 7000,
      tolStable: 1000,
      transWidth: 1.6,
      transHeight: 2.5,
      scale: 4.5,
      initVals: [0, 0],
      canTol: true,
      weightLow: 1.3,
      weightHigh: 2,
      weightTransHeight: 200,
    },
  ],
};

export { attractor };